### ISSUE TITLE
統合された docker-compose.yaml の作成

### ISSUE THREAD

**Issue by wakame-tech** [i-pu/ipu#12]
# docker-compose.yaml を root に設置
client と server で Dockerfile があるので，統一されたdocker-compose.yaml を作成したい．  

#### 設定すべき環境変数
- env: 今どの環境なのか ex) ENV=docker-compose, ENV=production 等
- client port
- server port
- server URL
- postgres の諸々の設定
- 他にもなにかあったらどうぞ ...

## しないこと
/client と /server にあるdocker-compose.yaml は消さない．
それぞれの test 用に残しておきたい

**Comment by hamadakafu** [comment]
いらねぇ気がしてきた

**Comment by hamadakafu** [comment]
いらねぇ
